CREATE DATABASE IF NOT EXISTS dbparticion1;
--
USE dbparticion1;
--
CREATE TABLE IF NOT EXISTS employees_partRANGE_YEAR1
( id INT NOT NULL AUTO_INCREMENT, 
fname VARCHAR(30),
 lname VARCHAR(30),
 hired DATE NOT NULL DEFAULT '1970-01-01',
 separated DATE NOT NULL DEFAULT '9999-12-31',
 job_code INT,
 store_id INT,
 PRIMARY KEY(id, hired)
)
PARTITION BY RANGE (YEAR(hired))
SUBPARTITION BY HASH (MONTH(hired))
(PARTITION p0 VALUES LESS THAN (1971)
(SUBPARTITION p0_dec,
SUBPARTITION p0_jan,
SUBPARTITION p0_feb,
SUBPARTITION p0_mar,
SUBPARTITION p0_apr,
SUBPARTITION p0_may,
SUBPARTITION p0_jun,
SUBPARTITION p0_jul,
SUBPARTITION p0_aug,
SUBPARTITION p0_sept,
SUBPARTITION p0_oct,
SUBPARTITION p0_nov),
PARTITION p1 VALUES LESS THAN (1976)
(SUBPARTITION p1_dec,
SUBPARTITION p1_jan,
SUBPARTITION p1_feb,
SUBPARTITION p1_mar,
SUBPARTITION p1_apr,
SUBPARTITION p1_may,
SUBPARTITION p1_jun,
SUBPARTITION p1_jul,
SUBPARTITION p1_aug,
SUBPARTITION p1_sept,
SUBPARTITION p1_oct,
SUBPARTITION p1_nov),
PARTITION p2 VALUES LESS THAN (1981)
(SUBPARTITION p2_dec,
SUBPARTITION p2_jan,
SUBPARTITION p2_feb,
SUBPARTITION p2_mar,
SUBPARTITION p2_apr,
SUBPARTITION p2_may,
SUBPARTITION p2_jun,
SUBPARTITION p2_jul,
SUBPARTITION p2_aug,
SUBPARTITION p2_sept,
SUBPARTITION p2_oct,
SUBPARTITION p2_nov),
PARTITION p3 VALUES LESS THAN (1986)
(SUBPARTITION p3_dec,
SUBPARTITION p3_jan,
SUBPARTITION p3_feb,
SUBPARTITION p3_mar,
SUBPARTITION p3_apr,
SUBPARTITION p3_may,
SUBPARTITION p3_jun,
SUBPARTITION p3_jul,
SUBPARTITION p3_aug,
SUBPARTITION p3_sept,
SUBPARTITION p3_oct,
SUBPARTITION p3_nov),
PARTITION p4 VALUES LESS THAN (1991)
(SUBPARTITION p4_dec,
SUBPARTITION p4_jan,
SUBPARTITION p4_feb,
SUBPARTITION p4_mar,
SUBPARTITION p4_apr,
SUBPARTITION p4_may,
SUBPARTITION p4_jun,
SUBPARTITION p4_jul,
SUBPARTITION p4_aug,
SUBPARTITION p4_sept,
SUBPARTITION p4_oct,
SUBPARTITION p4_nov),
PARTITION p5 VALUES LESS THAN (1996)
(SUBPARTITION p5_dec,
SUBPARTITION p5_jan,
SUBPARTITION p5_feb,
SUBPARTITION p5_mar,
SUBPARTITION p5_apr,
SUBPARTITION p5_may,
SUBPARTITION p5_jun,
SUBPARTITION p5_jul,
SUBPARTITION p5_aug,
SUBPARTITION p5_sept,
SUBPARTITION p5_oct,
SUBPARTITION p5_nov),
PARTITION p6 VALUES LESS THAN (2001)
(SUBPARTITION p6_dec,
SUBPARTITION p6_jan,
SUBPARTITION p6_feb,
SUBPARTITION p6_mar,
SUBPARTITION p6_apr,
SUBPARTITION p6_may,
SUBPARTITION p6_jun,
SUBPARTITION p6_jul,
SUBPARTITION p6_aug,
SUBPARTITION p6_sept,
SUBPARTITION p6_oct,
SUBPARTITION p6_nov),
PARTITION p7 VALUES LESS THAN (2006)
(SUBPARTITION p7_dec,
SUBPARTITION p7_jan,
SUBPARTITION p7_feb,
SUBPARTITION p7_mar,
SUBPARTITION p7_apr,
SUBPARTITION p7_may,
SUBPARTITION p7_jun,
SUBPARTITION p7_jul,
SUBPARTITION p7_aug,
SUBPARTITION p7_sept,
SUBPARTITION p7_oct,
SUBPARTITION p7_nov),
PARTITION p8 VALUES LESS THAN (2011)
(SUBPARTITION p8_dec,
SUBPARTITION p8_jan,
SUBPARTITION p8_feb,
SUBPARTITION p8_mar,
SUBPARTITION p8_apr,
SUBPARTITION p8_may,
SUBPARTITION p8_jun,
SUBPARTITION p8_jul,
SUBPARTITION p8_aug,
SUBPARTITION p8_sept,
SUBPARTITION p8_oct,
SUBPARTITION p8_nov),
PARTITION p9 VALUES LESS THAN (2016)
(SUBPARTITION p9_dec,
SUBPARTITION p9_jan,
SUBPARTITION p9_feb,
SUBPARTITION p9_mar,
SUBPARTITION p9_apr,
SUBPARTITION p9_may,
SUBPARTITION p9_jun,
SUBPARTITION p9_jul,
SUBPARTITION p9_aug,
SUBPARTITION p9_sept,
SUBPARTITION p9_oct,
SUBPARTITION p9_nov),
PARTITION p10 VALUES LESS THAN (2021)
(SUBPARTITION p10_dec,
SUBPARTITION p10_jan,
SUBPARTITION p10_feb,
SUBPARTITION p10_mar,
SUBPARTITION p10_apr,
SUBPARTITION p10_may,
SUBPARTITION p10_jun,
SUBPARTITION p10_jul,
SUBPARTITION p10_aug,
SUBPARTITION p10_sept,
SUBPARTITION p10_oct,
SUBPARTITION p10_nov),
PARTITION p11 VALUES LESS THAN (2026)
(SUBPARTITION p11_dec,
SUBPARTITION p11_jan,
SUBPARTITION p11_feb,
SUBPARTITION p11_mar,
SUBPARTITION p11_apr,
SUBPARTITION p11_may,
SUBPARTITION p11_jun,
SUBPARTITION p11_jul,
SUBPARTITION p11_aug,
SUBPARTITION p11_sept,
SUBPARTITION p11_oct,
SUBPARTITION p11_nov),
PARTITION p12 VALUES LESS THAN (MAXVALUE)
(SUBPARTITION p12_dec,
SUBPARTITION p12_jan,
SUBPARTITION p12_feb,
SUBPARTITION p12_mar,
SUBPARTITION p12_apr,
SUBPARTITION p12_may,
SUBPARTITION p12_jun,
SUBPARTITION p12_jul,
SUBPARTITION p12_aug,
SUBPARTITION p12_sept,
SUBPARTITION p12_oct,
SUBPARTITION p12_nov)
);
--
-- DESCRIBE employees_partRANGE_YEAR1;
--
-- SET GLOBAL local_infile = 1;
-- SHOW GLOBAL VARIABLES LIKE 'local_infile';
-- SHOW VARIABLES LIKE 'secure_file_priv';
--
LOAD DATA INFILE 'C:\\Users\\panos\\Desktop\\employees_data.csv'
INTO TABLE employees_partRANGE_YEAR1
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
(fname, lname, hired, separated, job_code, store_id);
-- IGNORE 1 LINES;
COMMIT;
--
-- SELECT COUNT(*) AS number_of_rows FROM employees_partRANGE_YEAR1;
--
-- SELECT * FROM employees_partRANGE_YEAR1 LIMIT 10;
--
-- TRUNCATE TABLE employees_partRANGE_YEAR1;
--
-- DROP TABLE IF EXISTS employees_partRANGE_YEAR1;
--
-- DROP DATABASE IF EXISTS dbparticion1;